안드로이드 스튜디오 조사 자료
hs-2191178-WooJuneCheon/OS-teamplay pull request #4
Opened 2022-11-16 15:26 UTC by you04111

피드백 부탁드립니다.

2022-11-17 06:34 UTC, YoonSeok00 commented
피드백

2022-11-17 07:41 UTC, hs-2191178-WooJuneCheon commented
수고하셨습니다.

2022-11-17 07:44 UTC, hs-2191178-WooJuneCheon approved these changes
수고하셨습니다.

2022-11-17 07:44 UTC, hs-2191178-WooJuneCheon requested changes
.

2022-11-17 07:45 UTC, hs-2191178-WooJuneCheon approved these changes

2022-11-20 10:28 UTC, hs-1871388-jiyeonyoo commented
수고하셨습니다 !!

2022-11-20 17:00 UTC, hs-1871388-jiyeonyoo approved these changes

2022-11-21 06:10 UTC, YoonSeok00 approved these changes
수고하셨습니다.

2022-11-21 06:35 UTC, merged